export const items = [
    { "name": "Modifiers", "link": "/us/Modifiers", "req": "" },
    { "name": "Distilled Emotions", "link": "/Distilled_Emotions", "req": "" },
    { "name": "Expedition Logbooks", "link": "/Expedition_Logbook", "req": "" },
    { "name": "Corrupteds", "link": "/Corrupted", "req": "" },
    { "name": "Strongboxes", "link": "/Strongbox", "req": "" },
    { "name": "Relics", "link": "/Relics", "req": "" },
    { "name": "Waystones", "link": "/Waystones", "req": "" },
    { "name": "Inscribed Ultimatums", "link": "/Inscribed_Ultimatum", "req": "" },
    { "name": "Claws", "link": "/us/Claws#ModifiersCalc", "req": "" },
    { "name": "Daggers", "link": "/us/Daggers#ModifiersCalc", "req": "" },
    { "name": "Wands", "link": "/us/Wands#ModifiersCalc", "req": "" },
    { "name": "One Hand Swords", "link": "/us/One_Hand_Swords#ModifiersCalc", "req": "" },
    { "name": "One Hand Axes", "link": "/us/One_Hand_Axes#ModifiersCalc", "req": "" },
    { "name": "One Hand Maces", "link": "/us/One_Hand_Maces#ModifiersCalc", "req": "" },
    { "name": "Sceptres", "link": "/us/Sceptres#ModifiersCalc", "req": "" },
    { "name": "Spears", "link": "/us/Spears#ModifiersCalc", "req": "" },
    { "name": "Flails", "link": "/us/Flails#ModifiersCalc", "req": "" },
    { "name": "Bows", "link": "/us/Bows#ModifiersCalc", "req": "" },
    { "name": "Staves", "link": "/us/Staves#ModifiersCalc", "req": "" },
    { "name": "Two Hand Swords", "link": "/us/Two_Hand_Swords#ModifiersCalc", "req": "" },
    { "name": "Two Hand Axes", "link": "/us/Two_Hand_Axes#ModifiersCalc", "req": "" },
    { "name": "Two Hand Maces", "link": "/us/Two_Hand_Maces#ModifiersCalc", "req": "" },
    { "name": "Quarterstaves", "link": "/us/Quarterstaves#ModifiersCalc", "req": "" },
    { "name": "Crossbows", "link": "/us/Crossbows#ModifiersCalc", "req": "" },
    { "name": "Traps", "link": "/us/Traps#ModifiersCalc", "req": "" },
    { "name": "Amulets", "link": "/us/Amulets#ModifiersCalc", "req": "" },
    { "name": "Rings", "link": "/us/Rings#ModifiersCalc", "req": "" },
    { "name": "Belts", "link": "/us/Belts#ModifiersCalc", "req": "" },
    { "name": "Gloves", "link": "/us/Gloves_str#ModifiersCalc", "req": "str" },
    { "name": "Gloves", "link": "/us/Gloves_dex#ModifiersCalc", "req": "dex" },
    { "name": "Gloves", "link": "/us/Gloves_int#ModifiersCalc", "req": "int" },
    { "name": "Gloves", "link": "/us/Gloves_str_dex#ModifiersCalc", "req": "str_dex" },
    { "name": "Gloves", "link": "/us/Gloves_str_int#ModifiersCalc", "req": "str_int" },
    { "name": "Gloves", "link": "/us/Gloves_dex_int#ModifiersCalc", "req": "dex_int" },
    { "name": "Boots", "link": "/us/Boots_str#ModifiersCalc", "req": "str" },
    { "name": "Boots", "link": "/us/Boots_dex#ModifiersCalc", "req": "dex" },
    { "name": "Boots", "link": "/us/Boots_int#ModifiersCalc", "req": "int" },
    { "name": "Boots", "link": "/us/Boots_str_dex#ModifiersCalc", "req": "str_dex" },
    { "name": "Boots", "link": "/us/Boots_str_int#ModifiersCalc", "req": "str_int" },
    { "name": "Boots", "link": "/us/Boots_dex_int#ModifiersCalc", "req": "dex_int" },
    { "name": "Body Armours", "link": "/us/Body_Armours_str#ModifiersCalc", "req": "str" },
    { "name": "Body Armours", "link": "/us/Body_Armours_dex#ModifiersCalc", "req": "dex" },
    { "name": "Body Armours", "link": "/us/Body_Armours_int#ModifiersCalc", "req": "int" },
    { "name": "Body Armours", "link": "/us/Body_Armours_str_dex#ModifiersCalc", "req": "str_dex" },
    { "name": "Body Armours", "link": "/us/Body_Armours_str_int#ModifiersCalc", "req": "str_int" },
    { "name": "Body Armours", "link": "/us/Body_Armours_dex_int#ModifiersCalc", "req": "dex_int" },
    { "name": "Body Armours", "link": "/us/Body_Armours_str_dex_int#ModifiersCalc", "req": "str_dex_int" },
    { "name": "Helmets", "link": "/us/Helmets_str#ModifiersCalc", "req": "str" },
    { "name": "Helmets", "link": "/us/Helmets_dex#ModifiersCalc", "req": "dex" },
    { "name": "Helmets", "link": "/us/Helmets_int#ModifiersCalc", "req": "int" },
    { "name": "Helmets", "link": "/us/Helmets_str_dex#ModifiersCalc", "req": "str_dex" },
    { "name": "Helmets", "link": "/us/Helmets_str_int#ModifiersCalc", "req": "str_int" },
    { "name": "Helmets", "link": "/us/Helmets_dex_int#ModifiersCalc", "req": "dex_int" },
    { "name": "Quivers", "link": "/us/Quivers#ModifiersCalc", "req": "" },
    { "name": "Foci", "link": "/us/Foci#ModifiersCalc", "req": "" },
    { "name": "Shields", "link": "/us/Shields_str#ModifiersCalc", "req": "str" },
    { "name": "Shields", "link": "/us/Shields_dex#ModifiersCalc", "req": "dex" },
    { "name": "Shields", "link": "/us/Shields_str_dex#ModifiersCalc", "req": "str_dex" },
    { "name": "Shields", "link": "/us/Shields_str_int#ModifiersCalc", "req": "str_int" },
    { "name": "Rubies", "link": "/us/Ruby#ModifiersCalc", "req": "" },
    { "name": "Emeralds", "link": "/us/Emerald#ModifiersCalc", "req": "" },
    { "name": "Sapphires", "link": "/us/Sapphire#ModifiersCalc", "req": "" },
    { "name": "Time-Lost Rubies", "link": "/us/Time-Lost_Ruby#ModifiersCalc", "req": "" },
    { "name": "Time-Lost Emeralds", "link": "/us/Time-Lost_Emerald#ModifiersCalc", "req": "" },
    { "name": "Time-Lost Sapphires", "link": "/us/Time-Lost_Sapphire#ModifiersCalc", "req": "" },
    { "name": "Life Flasks", "link": "/us/Life_Flasks#ModifiersCalc", "req": "" },
    { "name": "Mana Flasks", "link": "/us/Mana_Flasks#ModifiersCalc", "req": "" },
    { "name": "Charms", "link": "/us/Charms#ModifiersCalc", "req": "" },
    { "name": "Breach Precursor Tablets", "link": "/Breach_Precursor_Tablet", "req": "" },
    { "name": "Expedition Precursor Tablets", "link": "/Expedition_Precursor_Tablet", "req": "" },
    { "name": "Delirium Precursor Tablets", "link": "/Delirium_Precursor_Tablet", "req": "" }
];